server:
port: 8181
spring:
datasource:
driver-class-name: com.mysql.cj.jdbc.Driver
url: jdbc://localhost:3306/
username: root
password: root
jpa:
show-sql: true
ddl-auto: update
hibernate: 
dialect: org.hibernate.dialect.MySQL8Dialect